
name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: ${{ github.repository_owner != github.actor }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3